# Generated by Django 5.0.3 on 2024-03-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("watering_frequency", models.CharField(max_length=50)),
                ("sunlight_requirement", models.CharField(max_length=100)),
            ],
        ),
    ]
